<?php
/**
 * Copyright © 2009-2017 Vaimo Group. All rights reserved.
 * See LICENSE.txt for license details.
 */

use Dibs\EasyCheckout\Block\Checkout\Button;

/**
 * @var \Dibs\EasyCheckout\Block\Checkout\Button $block
 */
?>
<a class="action dibs_easy_checkout_button" href="<?php /* @escapeNotVerified */ echo $block->getCheckoutUrl()?>">
    <?php /* @escapeNotVerified */ echo __('Check Out with Dibs Easy Checkout');?>
</a>