<script type="text/javascript" src="<?php echo $block->getDibsCheckoutJsUrl() ?>"></script>
<div id="checkout">  

<div data-bind="scope: 'checkout'">
<!-- ko template: getTemplate() --><!-- /ko -->
</div>

<div id="dibs-easy-window">
    <div id="dibs-complete-checkout">
    </div>
    <div id="dibseasy-switch-checkout-mobile">
        <form action="<?= $block->getUrl('checkout') ?>">
            <button type="submit" class="btn btn-outline-primary">Use other payment method</button>
        </form>
    </div>
</div>
<div id="clear"></div>

</div>

<script type="text/x-magento-init">
        {
            "*": {
                "Magento_Ui/js/core/app": {
                    "components": {
                        "checkout": {
                            "component": "Dibs_EasyCheckout/js/checkout",
                            "template" : "Dibs_EasyCheckout/checkout/checkout",
                            "checkout" : {"checkoutKey": "<?php echo $block->getCheckoutKey()?>", 
                                          "paymentId": "<?php echo $block->getPaymentId() ?>",
                                          "containerId": "dibs-complete-checkout",
                                          "language": "<?php echo $block->getCheckoutLanguage() ?>",
                                          "updateview_url": "<?= $block->getUrl('dibs_easy/checkout/updateview')?>",
                                          "cart_url": "<?= $block->getUrl('checkout/cart')?>",
                                          "checkout_url": "<?= $block->getUrl('checkout/cart')?>",
                                          "start_url": "<?= $block->getUrl('dibs_easy/checkout/start')?>"
                              }
                        }
                    }
                }
            }
        }
</script>